baseURL = 'https://lee2856.github.io/'
languageCode = 'en-us'
title = 'Seunghoon Lee'
theme = "barks"

[params.head]
	author = "Seunghoon Lee"
	description = "I am a Ph.D. student in the Department of Computer Science at Purdue University."

[params.navigation]
	show_navigation = true

[params.footer]
	show_footer = true

[params.typography]
	title_font = "Raleway"
	body_font = "Raleway"

[params]
	favicon = "/static/favicon.ico"

[params.colors]
	link_color = "#2E64FE"

[params.social]
	[params.social.email]
		name = "E-Mail"
		class = "fas fa-envelope"
		url = "mailto:lee2856@purdue.edu"
		weight = 1
	[params.social.github]
		name = "GitHub"
		class = "fab fa-github"
		url = "https://github.com/lee2856"
		weight = 2
	[params.social.google_scholar]
		name = "Google Scholar"
		class = "fas fa-graduation-cap"
		url = "https://scholar.google.com/citations?user=fLWCOIgAAAAJ&hl=en"
		weight = 3
	[params.social.orcid]
		name = "Orcid"
		class = "fab fa-orcid"
		url = "https://orcid.org/my-orcid?orcid=0000-0003-4475-5686"
		weight = 4
	[params.social.linkedin]
		name = "LinkedIn"
		class = "fab fa-linkedin"
		url = "https://www.linkedin.com/in/seunghoon-lee-7673b1146/fr/"
		weight = 5

[[menu.main]]
	name = "Home"
	url = "/"
	weight = 1

[[menu.main]]
	name = "CV"
	url = "/myCV"
	weight = 2

[[menu.main]]
	name = "Publications"
	url = "/myPublications"
	weight = 3

[[menu.main]]
	name = "Talks"
	url = "/myTalks"
	weight = 4

[[menu.main]]
	name = "Teaching"
	url = "/myTeaching"
	weight = 5

[[menu.main]]
	name = "Others"
	url = "/others"
	weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
